import React from 'react';
import config from '../config';


export default props => {
  console.log('SummaryPage.render', props);

  return (
    <div className="page-break">
      <div className="header">
        <h1>Report Summary</h1>
      </div>
      <p dangerouslySetInnerHTML={{ __html: props.Top }} title={config.notProd && "ReportTextTable.Text(Top)"}></p>
      <p dangerouslySetInnerHTML={{ __html: props.Table1headingautogeneratedtable }}
        title={config.notProd && "ReportTextTable.Text(Table 1 heading...)"}></p>
      {'<table>'}
      <p dangerouslySetInnerHTML={{ __html: props.Table2headingautogeneratedtable }}
        title={config.notProd && "ReportTextTable.Text(Table 2 heading...)"}></p>
      {'<table>'}
      <p dangerouslySetInnerHTML={{ __html: props.Bottom }} title={config.notProd && "ReportTextTable.Text(Bottom)"}></p>
    </div>
  );
};
